"""What the project knows — the one place memory is assembled.

Before 2026-09-01 memory was not a thing, it was a projection into a run:
`known-findings.json` was built fresh into every RUN_DIR, capped at 300, and
outside a run nobody could reach it. This module has owned it since — the
projection into a run (`for_run`) is just one of its answers, next to the
full picture (`assemble`) and the selection for the next specialist in a
chain (`upstream`).

The truth stays in `.agency/runs/`. This module owns nothing — it reads and
assembles, so anything it returns can be rebuilt at any time. That holds even
for the one thing it writes: the committed bundle `.agency/knowledge/`
(`bundle()`) is a derived index of memory, not a second source of truth.
Deleting it and rebuilding is a safe operation — if it were not, that would
be a bug.

The bundle exists for a reader with no Agency: a bare session in the
repository, a colleague in an editor, a provider we do not know about today.
That is why it is markdown and not a database.
"""

from __future__ import annotations

import os
from pathlib import Path

from . import packs
from . import runs as _runs
from .config import Project
from .util import posix, write_json

#: How the project's memory is committed. Everything under `findings/` plus
#: `index.md` and `log.md` is generated by `bundle()`; `pages/` is written by
#: the specialists themselves at the end of a run.
BUNDLE = "knowledge"
LEDGER = "findings"
PAGES = "pages"

#: How many findings go into a run's projection. Memory tends to be small —
#: tens of findings, not thousands — so this is a generous ceiling, not a
#: ranking problem: what does not fit is simply the oldest.
FOR_RUN_FINDINGS = 300

#: How many runs are listed in the chronology. The cap is visible right in the
#: file — an unlisted run is not lost, it is one directory over.
LOG_RUNS = 50


def _view(run, rec: dict, finding: dict, decision: dict | None,
          notes: list[dict] | None) -> dict:
    """One finding as someone other than the run that found it sees it."""
    a = finding.get("anchor") or {}
    who = (rec.get("agent") or {}).get("hire")
    view = {
        "id": finding.get("id"), "title": finding.get("title"),
        "dimension": finding.get("dimension"), "severity": finding.get("severity"),
        "file": a.get("file"), "line": a.get("line"),
        "decision": decision["state"] if decision else None,
        "reason": decision.get("reason") if decision else None,
        # Who decided. The difference between "one model thinks so" and "a
        # second model confirmed it and a human accepted it" is the most
        # valuable thing on input, and it was lost as a single `decision`
        # string.
        "decidedBy": _runs.normalize_by(decision.get("by")) if decision else None,
        "runId": run.id,
        # Who found it. Without this there is no telling "a colleague on
        # another model already found this" from "I wrote this myself last
        # week".
        "hire": who, "pack": rec.get("pack"),
        "provider": (rec.get("agent") or {}).get("provider"),
    }
    if notes:
        view["notes"] = [{"text": n.get("text"),
                          "by": _runs.normalize_by(n.get("by")),
                          "at": n.get("at")} for n in notes]
    return view


def assemble(project: Project, exclude: str | None = None,
             only: list[str] | None = None, with_notes: bool = True) -> dict:
    """The whole attributed picture of the project — across runs, packs and
    workers.

    No cap. Whoever cannot carry the whole picture calls `for_run`; whoever
    needs it as a brief calls `upstream`.
    """
    findings: list[dict] = []
    specs: list[dict] = []
    for run in _runs.load_runs(project):
        if exclude and run.id == exclude:
            continue
        if only is not None and run.id not in only:
            continue
        rec = run.record()
        decided = _runs.decisions(run)
        threads = _runs.history(run) if with_notes else {}
        for f in run.findings():
            notes = [e for e in threads.get(f.get("id"), []) if e.get("kind") == "note"]
            findings.append(_view(run, rec, f, decided.get(f.get("id")), notes))
        if (run.dir / "specs").is_dir():
            for path in sorted((run.dir / "specs").rglob("*")):
                if path.is_file():
                    specs.append({"runId": run.id,
                                  "hire": (rec.get("agent") or {}).get("hire"),
                                  "path": posix(path.relative_to(project.root))})
    return {"findings": findings, "specs": specs}


# ------------------------------------------------------------------ pages

def installed_packs(project: Project) -> list[str]:
    return [p.name for p in packs.available(project)]


def pages_dir(project: Project, pack: str) -> Path:
    """Where a pack's curated knowledge lives."""
    return project.agency_dir / BUNDLE / PAGES / pack


def _stale_after_days(text: str, days: int = 60) -> bool:
    """Best-effort staleness from a leading `Last reviewed: YYYY-MM-DD` line.
    A page without one, or with an unparsable line, is simply not flagged —
    an older page is not a broken one."""
    import re
    from datetime import date
    m = re.match(r"^\s*Last reviewed:\s*(\d{4}-\d{2}-\d{2})", text)
    if not m:
        return False
    try:
        y, mo, d = (int(x) for x in m.group(1).split("-"))
        return (date.today() - date(y, mo, d)).days > days
    except ValueError:
        return False


def pages(project: Project, pack: str) -> list[dict]:
    """A pack's pages — plain markdown, one convention: a leading
    `Last reviewed: <date>` line. Written by the specialist at the end of a
    run, owned by the project. No frontmatter, no parser — a page a human
    wrote by hand must never be reported as "broken"."""
    d = pages_dir(project, pack)
    if not d.is_dir():
        return []
    found = []
    for path in sorted(d.glob("*.md")):
        text = path.read_text(encoding="utf-8", errors="replace")
        title = next((line.lstrip("#").strip() for line in text.splitlines()
                     if line.strip()), path.stem)
        found.append({"id": path.stem, "path": posix(path.relative_to(project.root)),
                     "title": title, "stale": _stale_after_days(text)})
    return found


def pages_summary(project: Project) -> dict:
    """State of every hired pack's pages — for `agency doctor` and `agency knowledge`."""
    out = {"total": 0, "stale": 0, "byPack": {}}
    for pack in installed_packs(project):
        found = pages(project, pack)
        if not found:
            continue
        out["byPack"][pack] = len(found)
        out["total"] += len(found)
        out["stale"] += len([p for p in found if p["stale"]])
    return out


def for_run(project: Project, run) -> dict:
    """What this project already knows — across runs, packs and specialists.

    Findings carry their decision with them: "this was already rejected as
    by-design" is the most valuable sentence a new run can be handed on
    input. Dedup after ingest is a safety net, not a substitute — a session
    that starts without knowing past findings is condemned to repeat them.

    Newest first, uncapped ranking: memory here is tens of findings, not
    thousands, so a plain recency cut is the whole story.
    """
    ev = run.dir / "evidence"
    ev.mkdir(parents=True, exist_ok=True)

    # Notes are a discussion thread; they belong in the brief for the next
    # specialist in a chain, not in a run's background.
    known = assemble(project, exclude=run.id, with_notes=False)

    picked = known["findings"][:FOR_RUN_FINDINGS]
    write_json(ev / "known-findings.json", picked)
    stats = {"knownFindings": len(known["findings"])}

    pack = run.record().get("pack") or ""
    own_pages = [p for p in pages(project, pack)] if pack else []
    if own_pages:
        # No cap: these are not someone else's findings in the background,
        # they are the specialist's own conclusions. Trimming them means
        # letting it arrive at one of them a second time.
        write_json(ev / "known-pages.json", own_pages)
        stats["knownPages"] = len(own_pages)
    if known["specs"]:
        write_json(ev / "known-specs.json", known["specs"])
        stats["knownSpecs"] = len(known["specs"])
    return stats


def upstream(project: Project, run_ids: list[str]) -> dict:
    """The selection handed to the next specialist — full, no cap.

    The difference from `for_run` is not the data, it is the role: this is
    not background, this is the brief. A finding that does not fit into the
    background is an inconvenience; a finding that does not fit into the
    brief is a finding the second specialist never decided on.
    """
    picked = [r for r in _runs.load_runs(project) if r.id in set(run_ids)]
    known = assemble(project, only=run_ids, with_notes=True)
    return {
        "runs": [{
            "id": r.id,
            "pack": r.record().get("pack"),
            "hire": (r.record().get("agent") or {}).get("hire"),
            "summary": summary(r),
        } for r in picked],
        **known,
    }


# ------------------------------------------------------------------ ledger

def _entries(project: Project) -> list[dict]:
    """Every finding, together with who wrote it and what happened to it
    since. Its own pass, not `assemble()`: the run projection is deliberately
    thin (a finding's body would bloat it) and the ledger is entirely about
    the text. Two answers to two questions, not one function with two modes.
    """
    found: list[dict] = []
    for run in _runs.load_runs(project):
        rec = run.record()
        pack = rec.get("pack") or "unknown"
        agent = rec.get("agent") or {}
        who = agent.get("hire") or _runs.worker_id(pack, provider=agent.get("provider"))
        events = _runs.history(run)
        for f in run.findings():
            found.append({
                "finding": f, "run": run, "pack": pack,
                "by": f"hire:{who}",
                "at": rec.get("finishedAt") or rec.get("startedAt"),
                "events": [e for e in events.get(f.get("id")) or []
                           if e.get("kind", "decision") == "decision"],
            })
    return found


def _root_id(by_id: dict, fid: str | None) -> str | None:
    """The root of a duplicate family. A cycle or a pointer into a discarded
    run both end here."""
    seen: set[str] = set()
    while fid in by_id and fid not in seen:
        seen.add(fid)
        nxt = by_id[fid]["finding"].get("duplicateOf")
        if not nxt or nxt not in by_id:
            break
        fid = nxt
    return fid


def _is_human(by: str | None) -> bool:
    v = _runs.normalize_by(by) or ""
    return v == _runs.HUMAN or v.startswith(_runs.HUMAN + ":")


#: How much scrutiny a finding has had so far. Not the same as `verified`, on
#: purpose: `verified` confirms a CLAIM, `trust` is a measure of review. A
#: rejected finding is `human-reviewed` AND `status: deprecated` at once — a
#: human looked at it and the claim did not hold. As one field, one of those
#: two sentences could not be written.
TIERS = ("unverified", "machine-confirmed", "human-reviewed")

#: State of the claim. `deferred` is not `draft` — a deferred finding still
#: holds, only nothing is being done about it right now.
STATUS_BY_DECISION = {"accepted": "stable", "deferred": "stable", "rejected": "deprecated"}


def _concept(members: list[dict], origin: dict) -> dict:
    """A duplicate family as one finding — with who confirmed it."""
    f = origin["finding"]
    a = f.get("anchor") or {}
    sym = (a.get("symbol") or {}).get("name")

    # A duplicate from the SAME worker is not an independent confirmation, it
    # is the same worker a second time.
    confirmations = [m for m in members if m is not origin and m["by"] != origin["by"]]
    events = sorted((e for m in members for e in m["events"]), key=lambda e: e.get("at") or "")
    decision = events[-1] if events else None
    peers = [e for e in events
             if not _is_human(e.get("by")) and _runs.normalize_by(e.get("by")) != origin["by"]]

    if any(_is_human(e.get("by")) for e in events):
        trust = "human-reviewed"
    elif confirmations or peers:
        trust = "machine-confirmed"
    else:
        trust = "unverified"

    verified = [{"by": m["by"], "at": m["at"], "how": "independent-duplicate"}
                for m in confirmations]
    verified += [{"by": _runs.normalize_by(e.get("by")), "at": e.get("at"), "how": "accepted"}
                 for e in peers if e.get("state") == "accepted"]

    return {
        "id": f.get("id"),
        "title": f.get("title") or f.get("id"),
        "body": f.get("body") or "",
        "pack": origin["pack"],
        "dimension": f.get("dimension"),
        "severity": f.get("severity"),
        "status": STATUS_BY_DECISION.get(decision["state"], "draft") if decision else "draft",
        "trust": trust,
        "generated": {"by": origin["by"], "at": origin["at"]},
        "verified": verified,
        "decision": ({"state": decision["state"], "reason": decision.get("reason"),
                      "by": _runs.normalize_by(decision.get("by")), "at": decision.get("at")}
                     if decision else None),
        "anchor": {"file": a.get("file"), "line": a.get("line"),
                   "commit": a.get("commit"), "symbol": sym},
        "sources": [{"resource": f"agency://run/{origin['run'].id}"}]
                   + [{"resource": e.get("source"), "note": e.get("detail")}
                      for e in (f.get("evidence") or []) if e.get("source")],
        "trail": [{"by": m["by"], "at": m["at"], "run": m["run"].id,
                   "how": "found" if m is origin else "found again", "note": None}
                  for m in members]
                 + [{"by": _runs.normalize_by(e.get("by")), "at": e.get("at"),
                     "run": None, "how": e["state"], "note": e.get("reason")}
                    for e in events],
        "occurrences": len(members),
    }


def ledger(project: Project) -> list[dict]:
    """Findings across runs, with duplicates folded into families.

    A duplicate is not another finding, it is a second worker at the same
    finding — and that is exactly what turns it into `verified`. If it had
    its own file, the ledger would claim the project found twice as much as
    it did.
    """
    entries = _entries(project)
    by_id = {e["finding"].get("id"): e for e in entries if e["finding"].get("id")}
    families: dict[str, list[dict]] = {}
    for e in entries:
        families.setdefault(_root_id(by_id, e["finding"].get("id")), []).append(e)

    out = []
    for rid, members in families.items():
        members.sort(key=lambda m: m["run"].id)
        origin = next((m for m in members if m["finding"].get("id") == rid), members[0])
        out.append(_concept(members, origin))
    return sorted(out, key=lambda c: c["id"] or "", reverse=True)


# ------------------------------------------------------------------ bundle

#: Groups in the overview. Rejected ones are deliberately not dropped: "this
#: was already rejected as by-design" is the most valuable sentence a later
#: run can be handed, and an overview that dropped it would hide the sentence
#: from anyone looking.
GROUPS = (
    ("open", "Open — nobody has decided yet"),
    ("accepted", "Accepted"),
    ("deferred", "Deferred"),
    ("rejected", "Rejected — do not report these again"),
)


def _frontmatter(front: dict) -> str:
    """A tiny, hand-rolled YAML-ish writer for the ledger's own generated
    files. Nothing ever reads these back — `bundle()` compares raw text — so
    a full parser is not needed, only a writer that quotes what it must."""
    import json as _json

    def emit(value, indent: int) -> list[str]:
        pad = "  " * indent
        if isinstance(value, dict):
            lines = []
            for k, v in value.items():
                if v is None or v == [] or v == {}:
                    lines.append(f"{pad}{k}: {_json.dumps(v, ensure_ascii=False) if v is not None else 'null'}")
                elif isinstance(v, (dict, list)):
                    lines.append(f"{pad}{k}:")
                    lines += emit(v, indent + 1)
                else:
                    lines.append(f"{pad}{k}: {_json.dumps(v, ensure_ascii=False)}")
            return lines
        if isinstance(value, list):
            lines = []
            for item in value:
                if isinstance(item, dict):
                    sub = emit(item, indent + 1)
                    lines.append(f"{pad}- {sub[0].strip()}" if sub else f"{pad}- {{}}")
                    lines += sub[1:]
                else:
                    lines.append(f"{pad}- {_json.dumps(item, ensure_ascii=False)}")
            return lines
        return [f"{pad}{_json.dumps(value, ensure_ascii=False)}"]

    return "---\n" + "\n".join(emit(front, 0)) + "\n---"


def _cell(text: str | None) -> str:
    """A table cell. A pipe in the title would break the columns."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _rel_link(from_dir: Path, target: Path) -> str:
    """A link from the bundle elsewhere in the repo. A pack's pages need not
    be inside it."""
    return posix(os.path.relpath(target, from_dir))


def _where(anchor: dict) -> str:
    f, line = anchor.get("file"), anchor.get("line")
    if not f:
        return ""
    return f"{f}:{line}" if line else f


def _finding_md(c: dict) -> str:
    """One finding as a concept — readable in an editor, machine-generated."""
    front = {
        "type": "Finding",
        "title": c["title"],
        "status": c["status"],
        "trust": c["trust"],
        "tags": [t for t in (f"pack/{c['pack']}",
                             f"dimension/{c['dimension']}" if c["dimension"] else None,
                             f"severity/{c['severity']}" if c["severity"] else None) if t],
        "generated": c["generated"],
        "verified": c["verified"],
        "decision": c["decision"],
        "anchor": c["anchor"],
        "occurrences": c["occurrences"] if c["occurrences"] > 1 else None,
        "sources": c["sources"],
    }

    body = [c["body"].strip()]
    where = _where(c["anchor"])
    if where:
        # The link goes from `.agency/knowledge/findings/` to the project
        # root, so it opens with a click in an editor — no Agency, no tool.
        commit = (c["anchor"].get("commit") or "")[:8]
        at = f" · commit `{commit}`" if commit else ""
        body.append(f"**Where:** [`{where}`](../../../{c['anchor']['file']}){at}")

    trail = ["**Trail**", ""]
    for t in c["trail"]:
        run = f" — [run {t['run'][:8]}](../../runs/{t['run']}/)" if t.get("run") else ""
        when = f" · {t['at'][:10]}" if t.get("at") else ""
        note = f" — {t['note']}" if t.get("note") else ""
        trail.append(f"- {t['how']} by `{t['by']}`{run}{note}{when}")
    body.append("\n".join(trail))

    return _frontmatter(front) + "\n\n" + "\n\n".join(x for x in body if x) + "\n"


def _index_md(project: Project, concepts: list[dict]) -> str:
    by_state: dict[str, list[dict]] = {}
    for c in concepts:
        state = (c["decision"] or {}).get("state") or "open"
        by_state.setdefault(state, []).append(c)

    confirmed = len([c for c in concepts if c["trust"] != "unverified"])
    tally = " · ".join([f"**{len(concepts)} finding{'' if len(concepts) == 1 else 's'}**"]
                       + [f"{len(by_state[s])} {s}" for s, _ in GROUPS if by_state.get(s)]
                       + ([f"{confirmed} reviewed by a second reader"] if confirmed else []))

    lines = [
        "# What this project knows",
        "",
        "Generated from `.agency/runs/` — `agency ingest` refreshes it after every "
        "run and `agency knowledge --rebuild` rewrites it from scratch. Edits here "
        "are overwritten; the truth is in the run directories.",
        "",
        tally + " · [run log](log.md)",
        "",
    ]

    for state, heading in GROUPS:
        group = by_state.get(state)
        if not group:
            continue
        lines += [f"## {heading}", "",
                  "| finding | severity | where | found by | reviewed |",
                  "|---|---|---|---|---|"]
        for c in group:
            reason = (c["decision"] or {}).get("reason")
            reviewed = c["trust"] + (f" · {reason}" if reason else "")
            lines.append(
                f"| [{_cell(c['title'])}]({LEDGER}/{c['id']}.md) "
                f"| {c['severity'] or ''} | `{_where(c['anchor'])}` "
                f"| `{c['generated']['by']}` | {reviewed} |")
        lines.append("")

    by_pack = [(pack, pages(project, pack)) for pack in installed_packs(project)]
    by_pack = [(pack, own) for pack, own in by_pack if own]
    if by_pack:
        lines += ["## Pages", "",
                  "Written by the specialist at the end of a run — conclusions, "
                  "not a log. The chronology of runs is in [`log.md`](log.md).", ""]
    for pack, own in by_pack:
        rel = _rel_link(project.agency_dir / BUNDLE, pages_dir(project, pack))
        lines += [f"### {pack}", "", "| page | |", "|---|---|"]
        for p in own:
            flag = "stale" if p["stale"] else ""
            lines.append(f"| [{_cell(p['title'])}]({rel}/{p['id']}.md) | {flag} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _log_md(project: Project) -> str:
    all_runs = _runs.load_runs(project)
    lines = [
        "# Run log",
        "",
        "Newest first. Each entry is the summary the specialist left behind "
        "(`RUN_DIR/summary.md`) — its own words, not a rendering of the findings.",
        "",
    ]
    for run in all_runs[:LOG_RUNS]:
        rec = run.record()
        agent = rec.get("agent") or {}
        pack = rec.get("pack") or "unknown"
        who = agent.get("hire") or _runs.worker_id(pack, provider=agent.get("provider"))
        when = (rec.get("startedAt") or "")[:10]
        counts = rec.get("counts") or {}
        kept = counts.get("kept", 0)
        tally = (f"{counts.get('raw', 0)} written → {kept} candidate{'' if kept == 1 else 's'}"
                 if counts else rec.get("status") or "")
        lines += [f"## {when} · {pack} · `hire:{who}`", "",
                  f"[run {run.id}](../runs/{run.id}/) · {tally}", ""]
        text = summary(run)
        lines += [text if text else "_No summary left behind._", ""]

    if len(all_runs) > LOG_RUNS:
        lines += [f"_{len(all_runs) - LOG_RUNS} older runs are not listed here — "
                  f"they are in `.agency/runs/`._", ""]
    return "\n".join(lines).rstrip() + "\n"


def _bundle_files(project: Project) -> dict[str, str]:
    """What the bundle should contain. A pure function over the runs — so it
    can be compared with what is on disk without rewriting anything.

    Nothing here carries a generation timestamp: if it did, every rebuild
    would rewrite the whole bundle and `git diff` would stop answering what
    actually changed.
    """
    if not _runs.load_runs(project):
        return {}
    concepts = ledger(project)
    files = {f"{LEDGER}/{c['id']}.md": _finding_md(c) for c in concepts}
    files["index.md"] = _index_md(project, concepts)
    files["log.md"] = _log_md(project)
    return files


def bundle(project: Project, write: bool = True) -> dict:
    """Writes (or just compares) `.agency/knowledge/`.

    The bundle is derived — the same status as any other cache. If it became
    a source of truth, one bad rewrite would erase the decision history;
    instead it can be discarded and rebuilt from `.agency/runs/` at any time.
    """
    root = project.agency_dir / BUNDLE
    want = _bundle_files(project)

    have: dict[str, str] = {}
    for name in ("index.md", "log.md"):
        if (root / name).is_file():
            have[name] = (root / name).read_text(encoding="utf-8")
    for path in sorted((root / LEDGER).glob("*.md")) if (root / LEDGER).is_dir() else []:
        have[f"{LEDGER}/{path.name}"] = path.read_text(encoding="utf-8")

    changed = sorted(name for name, text in want.items() if have.get(name) != text)
    # A discarded run must disappear from the ledger too. Only what the
    # bundle generates is removed — `pages/` is written by hand and untouched.
    removed = sorted(name for name in have if name not in want)

    if write:
        for name in changed:
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(want[name])
        for name in removed:
            (root / name).unlink()

    return {"path": posix(root), "findings": len(want) - 2 if want else 0,
            "changed": changed, "removed": removed, "written": write}


def summary(run) -> str | None:
    """The summary a run left behind (`RUN_DIR/summary.md`), or nothing.

    The contract is in each pack's `SKILL.md`. The core neither produces it
    nor edits it: the summary is the one place a specialist speaks in its own
    words, and writing it on its behalf would mean fabricating a record of
    someone else's work.
    """
    path = run.dir / "summary.md"
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8").strip()
    return text or None
